# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
import numpy as np

# Print NumPy version
print("NumPy version:", np.__version__)

# Show NumPy build configuration
print("\nNumPy configuration:")
np.show_config()

NumPy version: 2.3.4

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: sci

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
import numpy as np

# Way 1: Random values from a uniform distribution over [0, 1)
a = np.random.rand(2, 3, 5)

# Way 2: Random values from a standard normal distribution (mean=0, std=1)
a = np.random.randn(2, 3, 5)

# Way 3: Random integers between 0 and 100 (exclusive)
a = np.random.randint(0, 100, size=(2, 3, 5))


### 4. Print a.


In [4]:
### [your code here]
print (a)

[[[78 89  7 21 69]
  [20 37  5  5 28]
  [ 0 99 12 59 44]]

 [[ 8 64 76 44 35]
  [22 24 46 64 97]
  [81 32 64  6 43]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
import numpy as np

# Create a 5x2x3 array filled with ones
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
### [your code here]
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
# Check if a and b have the same number of elements
same_size = a.size == b.size

print("Do a and b have the same size?", same_size)
print("Size of a:", a.size)
print("Size of b:", b.size)

Do a and b have the same size? True
Size of a: 30
Size of b: 30



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
import numpy as np

# Transpose b to match the shape of a: from (5, 2, 3) to (2, 3, 5)
c = b.transpose(1, 2, 0)

# Verificación
print("Shape of a:", a.shape)
print("Shape of c:", c.shape)

Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
# Add a and c (both now have shape (2, 3, 5))
d = a + c

print("Shape of d:", d.shape)
print("Sample values from d:\n", d)

Shape of d: (2, 3, 5)
Sample values from d:
 [[[ 79.  90.   8.  22.  70.]
  [ 21.  38.   6.   6.  29.]
  [  1. 100.  13.  60.  45.]]

 [[  9.  65.  77.  45.  36.]
  [ 23.  25.  47.  65.  98.]
  [ 82.  33.  65.   7.  44.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
### [your code here]
# Print both arrays
print("Array a (random values):")
print(a)

print("\nArray d (a + c, where c is all ones):")
print(d)

# Explain the relationship
print("\nExplanation:")
print("Since c is an array of ones with the same shape as a,")
print("every element in d is exactly 1 greater than the corresponding element in a.")
print("In other words: d = a + 1")


Array a (random values):
[[[78 89  7 21 69]
  [20 37  5  5 28]
  [ 0 99 12 59 44]]

 [[ 8 64 76 44 35]
  [22 24 46 64 97]
  [81 32 64  6 43]]]

Array d (a + c, where c is all ones):
[[[ 79.  90.   8.  22.  70.]
  [ 21.  38.   6.   6.  29.]
  [  1. 100.  13.  60.  45.]]

 [[  9.  65.  77.  45.  36.]
  [ 23.  25.  47.  65.  98.]
  [ 82.  33.  65.   7.  44.]]]

Explanation:
Since c is an array of ones with the same shape as a,
every element in d is exactly 1 greater than the corresponding element in a.
In other words: d = a + 1



### 12. Multiply a and c. Assign the result to e.


In [14]:
### [your code here]
# Multiply a and c element-wise and store the result in e
e = a * c

# Print basic info
print("Shape of e:", e.shape)
print("Sample values from e:")
print(e)

# ------------------------------------------------------------------
# Since c is an array of ones with the same shape as a,
# every element in e equals the corresponding element in a multiplied by 1.
# Therefore, e is identical to a.
# In short:  e = a * 1  -->  e = a
# ------------------------------------------------------------------

Shape of e: (2, 3, 5)
Sample values from e:
[[[78. 89.  7. 21. 69.]
  [20. 37.  5.  5. 28.]
  [ 0. 99. 12. 59. 44.]]

 [[ 8. 64. 76. 44. 35.]
  [22. 24. 46. 64. 97.]
  [81. 32. 64.  6. 43.]]]




### 13. Does e equal to a? Why or why not?


In [15]:
### [your code here]
# Check whether e and a are numerically identical
are_equal = np.array_equal(e, a)

print("Does e equal a?", are_equal)

# ------------------------------------------------------------------
# e was obtained by element-wise multiplication of a and c.
# c is an array of ones, so each element of e is a[i,j,k] * 1.
# Multiplying by 1 does not change the value, hence e is numerically
# identical to a. Floating-point rounding errors are not expected here
# because 1.0 is exactly representable and multiplication by 1.0 is exact.
# ------------------------------------------------------------------


Does e equal a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [16]:
### [your code here]
# Extract summary statistics from array d
d_max = d.max()     # highest value in d
d_min = d.min()     # lowest value in d
d_mean = d.mean()   # arithmetic mean of all values in d

# ------------------------------------------------------------------
# .max(), .min(), and .mean() are NumPy methods that compute the
# maximum, minimum, and arithmetic-mean values across the entire array.
# Because d = a + 1, these statistics will each be exactly 1 greater
# than the corresponding statistic of the original random array a.
# ------------------------------------------------------------------

print("d_max :", d_max)
print("d_min :", d_min)
print("d_mean:", d_mean)


d_max : 100.0
d_min : 1.0
d_mean: 43.63333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
### [your code here]
# Create an uninitialized
f = np.empty((2, 3, 5))

# ------------------------------------------------------------------
# Step-by-step notes
# ------------------------------------------------------------------
# 1. np.empty allocates memory for the array but leaves the values
#    untouched (whatever was already in RAM).
# 2. The shape is identical to a (2x3x5), so we can later fill it
#    based on thresholds like d_min, d_mean, and d_max.
# ------------------------------------------------------------------

print("Shape of f:", f.shape)
print("Sample (uninitialized) values from f:")
print(f)

Shape of f: (2, 3, 5)
Sample (uninitialized) values from f:
[[[78. 89.  7. 21. 69.]
  [20. 37.  5.  5. 28.]
  [ 0. 99. 12. 59. 44.]]

 [[ 8. 64. 76. 44. 35.]
  [22. 24. 46. 64. 97.]
  [81. 32. 64.  6. 43.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [18]:
### [your code here]
# Populate f based on the rules given
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                f[i, j, k] = 0
            elif val == d_max:
                f[i, j, k] = 100
            elif val == d_mean:
                f[i, j, k] = 50
            elif d_min < val < d_mean:
                f[i, j, k] = 25
            elif d_mean < val < d_max:
                f[i, j, k] = 75

# ------------------------------------------------------------------
# Step-by-step notes
# ------------------------------------------------------------------
# 1. Iterate over every element of d using triple-index loops.
# 2. Compare each value against d_min, d_mean, and d_max.
# 3. Assign the specified code (0, 25, 50, 75, or 100) to the
#    corresponding position in f.
# 4. After the loops, f contains only the five allowed values.
# ------------------------------------------------------------------

print("f after population:")
print(f)

f after population:
[[[ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  25.  25.]
  [  0. 100.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [19]:
### [your code here]
# Display both arrays side-by-side
print("d:")
print(d)
print("\nf:")
print(f)

# ------------------------------------------------------------------
# Quick check: verify that f contains only the allowed values
unique_vals = np.unique(f)
print("\nUnique values in f:", unique_vals)
# ------------------------------------------------------------------
# Expected observation:
# Every entry in f should be one of {0, 25, 50, 75, 100}, matching
# the thresholds derived from d_min, d_mean, and d_max.
# ------------------------------------------------------------------

d:
[[[ 79.  90.   8.  22.  70.]
  [ 21.  38.   6.   6.  29.]
  [  1. 100.  13.  60.  45.]]

 [[  9.  65.  77.  45.  36.]
  [ 23.  25.  47.  65.  98.]
  [ 82.  33.  65.   7.  44.]]]

f:
[[[ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  25.  25.]
  [  0. 100.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]]]

Unique values in f: [  0.  25.  75. 100.]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [20]:
### [your code here]

# Create an empty array of strings with the same shape as d
f_str = np.empty(d.shape, dtype='<U1')   # '<U1' = single-character string

# Populate it with letters A-E according to the same rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                f_str[i, j, k] = 'A'
            elif val == d_max:
                f_str[i, j, k] = 'E'
            elif val == d_mean:
                f_str[i, j, k] = 'C'
            elif d_min < val < d_mean:
                f_str[i, j, k] = 'B'
            elif d_mean < val < d_max:
                f_str[i, j, k] = 'D'

print("f with string labels:")
print(f_str)

f with string labels:
[[['D' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['A' 'E' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'B' 'D']]]
